
package com.webserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EncryptService", targetNamespace = "http://www.webserver.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EncryptService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encryptString", targetNamespace = "http://www.webserver.com/", className = "com.webserver.EncryptString")
    @ResponseWrapper(localName = "encryptStringResponse", targetNamespace = "http://www.webserver.com/", className = "com.webserver.EncryptStringResponse")
    @Action(input = "http://www.webserver.com/EncryptService/encryptStringRequest", output = "http://www.webserver.com/EncryptService/encryptStringResponse")
    public String encryptString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "decryptString", targetNamespace = "http://www.webserver.com/", className = "com.webserver.DecryptString")
    @ResponseWrapper(localName = "decryptStringResponse", targetNamespace = "http://www.webserver.com/", className = "com.webserver.DecryptStringResponse")
    @Action(input = "http://www.webserver.com/EncryptService/decryptStringRequest", output = "http://www.webserver.com/EncryptService/decryptStringResponse")
    public String decryptString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
