
package com.webserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EncryptServiceService", targetNamespace = "http://www.webserver.com/", wsdlLocation = "http://localhost:8085/ws_server/encrypt?wsdl")
public class EncryptServiceService
    extends Service
{

    private final static URL ENCRYPTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ENCRYPTSERVICESERVICE_EXCEPTION;
    private final static QName ENCRYPTSERVICESERVICE_QNAME = new QName("http://www.webserver.com/", "EncryptServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/ws_server/encrypt?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENCRYPTSERVICESERVICE_WSDL_LOCATION = url;
        ENCRYPTSERVICESERVICE_EXCEPTION = e;
    }

    public EncryptServiceService() {
        super(__getWsdlLocation(), ENCRYPTSERVICESERVICE_QNAME);
    }

    public EncryptServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENCRYPTSERVICESERVICE_QNAME, features);
    }

    public EncryptServiceService(URL wsdlLocation) {
        super(wsdlLocation, ENCRYPTSERVICESERVICE_QNAME);
    }

    public EncryptServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENCRYPTSERVICESERVICE_QNAME, features);
    }

    public EncryptServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EncryptServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EncryptService
     */
    @WebEndpoint(name = "EncryptServicePort")
    public EncryptService getEncryptServicePort() {
        return super.getPort(new QName("http://www.webserver.com/", "EncryptServicePort"), EncryptService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EncryptService
     */
    @WebEndpoint(name = "EncryptServicePort")
    public EncryptService getEncryptServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserver.com/", "EncryptServicePort"), EncryptService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENCRYPTSERVICESERVICE_EXCEPTION!= null) {
            throw ENCRYPTSERVICESERVICE_EXCEPTION;
        }
        return ENCRYPTSERVICESERVICE_WSDL_LOCATION;
    }

}
